name: circleslate
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.5
  dotted_border: ^2.0.0
  http: ^1.2.2
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  pull_to_refresh: ^2.0.0
  uuid: ^4.5.1
  url_launcher: ^6.1.10
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.3
  internet_connection_checker_plus: ^2.9.0
  timeago: ^3.5.0
  lottie: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"
    remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animation/No Internet!.json



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700

    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: Roboto-Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

